# Generated by Django 5.2 on 2025-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car1_delete_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car1',
        ),
    ]
