# Generated by Django 5.2 on 2025-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_description_alter_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=300)),
                ('Car_description', models.TextField(max_length=1000)),
                ('Car_colour', models.CharField(max_length=200)),
                ('Car_image', models.ImageField(upload_to='Car')),
            ],
        ),
    ]
