# Generated by Django 5.2 on 2025-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Car_colour',
        ),
    ]
