# Generated by Django 5.2 on 2025-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Student_image', models.ImageField(upload_to='student')),
                ('English', models.TextField(max_length=100)),
                ('Science', models.TextField(max_length=100)),
                ('Maths', models.TextField(max_length=100)),
                ('Gujarati', models.TextField(max_length=100)),
                ('Computer', models.TextField(max_length=100)),
                ('Sanskrit', models.TextField(max_length=100)),
                ('Hindi', models.TextField(max_length=100)),
            ],
        ),
    ]
