# Generated by Django 5.2 on 2025-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adm_Name', models.CharField(max_length=200)),
                ('Adm_Email', models.EmailField(max_length=254)),
                ('Adm_Contact', models.IntegerField()),
                ('Adm_Password', models.TextField()),
                ('Adm_Role', models.TextField()),
                ('Adm_Status', models.BooleanField()),
            ],
        ),
    ]
